### ISSUE TITLE
trackHandledException logs exception as a "Crash" in Application Insights Dashboard

### ISSUE THREAD

**Issue by walkerc4** [Microsoft/ApplicationInsights-Android#31]
Have a few places where we log exceptions that aren't a crash but malformed data or something else that is recoverable.

```
TelemetryClient.trackHandledException(exception)
```

Logs this just like an uncaught exception in the portal even though the name is "Handled Exception."

I guess this will just have to be logged as a normal event?

**Comment by ghost** [comment]
For now using custom events would be the way to go since handled and unhandled exceptions are currently displayed together.

**Comment by romainpiel** [comment]
Is it an API issue limitation? Because it looks like Azure application insights can make the distinction between handled and unhandled exceptions.
In the attached there should be somethink like 3 unhandled vs 17 handles exceptions and I'm seeing 20 unhandled exceptions.

![screen shot 2015-05-11 at 11 09 28](https://cloud.githubusercontent.com/assets/464320/7562701/45432e38-f7ce-11e4-90ab-65002ad23bf3.png)

**Comment by ghost** [comment]
This is a known limitation and it is on our list to look into it.
